export const colorsInputTable = [
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-all-toggle-switch",
    inputValue: "",
    dataSetFirstColor: "",
    dataSetSecondColor: "",
    colorTitle: "all",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-black-and-white-toggle-switch",
    inputValue: "black_and_white",
    dataSetFirstColor: "black",
    dataSetSecondColor: "white",
    colorTitle: "black_and_white",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-black-toggle-switch",
    inputValue: "black",
    dataSetFirstColor: "black",
    dataSetSecondColor: "black",
    colorTitle: "black",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-white-toggle-switch",
    inputValue: "white",
    dataSetFirstColor: "white",
    dataSetSecondColor: "white",
    colorTitle: "white",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-yellow-toggle-switch",
    inputValue: "yellow",
    dataSetFirstColor: "yellow",
    dataSetSecondColor: "yellow",
    colorTitle: "yellow",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-orange-toggle-switch",
    inputValue: "orange",
    dataSetFirstColor: "orange",
    dataSetSecondColor: "orange",
    colorTitle: "orange",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-red-toggle-switch",
    inputValue: "red",
    dataSetFirstColor: "red",
    dataSetSecondColor: "red",
    colorTitle: "red",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-purple-toggle-switch",
    inputValue: "purple",
    dataSetFirstColor: "purple",
    dataSetSecondColor: "purple",
    colorTitle: "purple",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-magenta-toggle-switch",
    inputValue: "magenta",
    dataSetFirstColor: "magenta",
    dataSetSecondColor: "magenta",
    colorTitle: "magenta",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-green-toggle-switch",
    inputValue: "green",
    dataSetFirstColor: "green",
    dataSetSecondColor: "green",
    colorTitle: "green",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-teal-toggle-switch",
    inputValue: "teal",
    dataSetFirstColor: "teal",
    dataSetSecondColor: "teal",
    colorTitle: "teal",
  },
  {
    inputType: "radio",
    inputName: "color-toggle-switch",
    inputId: "color-blue-toggle-switch",
    inputValue: "blue",
    dataSetFirstColor: "blue",
    dataSetSecondColor: "blue",
    colorTitle: "blue",
  },
];
